# Configuration for the Medical Transcription App

# Database settings
database:
  development:
    url: "postgresql://postgres:123456789@localhost:5432/medical_transcription_dev"
    engine_options:
      pool_recycle: 300
      pool_pre_ping: true
  testing:
    url: "postgresql://postgres:123456789@localhost:5432/medical_transcription_test"
    engine_options:
      pool_recycle: 300
      pool_pre_ping: true
  production:
    url: "postgresql://postgres:123456789@localhost:5432/medical_transcription_prod"
    engine_options:
      pool_recycle: 3600
      pool_pre_ping: true
      pool_size: 10
      max_overflow: 20

# Authentication settings
auth:
  jwt_secret_key: "your-secure-jwt-secret-key-change-this-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# Application security
security:
  secret_key: "your-flask-secret-key-for-session-management-change-this-in-production"

# Environment-specific settings
environment:
  development:
    port: 2000
    debug: true
  testing:
    port: 2001
    debug: true
  production:
    port: 8000
    debug: false

# Storage settings
storage:
  upload_directory: "uploads"
  allowed_audio_extensions: [".wav", ".mp3", ".m4a", ".flac"]
  max_upload_size: 50000000  # 50MB

# External services
services:
  speech_recognition:
    default_language: "en-US"

  translation:
    default_source_language: "en"
    default_target_language: "es"

  tts:
    output_directory: "tts_output"

  # Redis configuration
  redis:
    url: "redis://localhost:6379/0"
    password: null  # Set to your Redis password if needed
    ssl: false
    connection_pool:
      max_connections: 10

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]"
  file: "/tmp/app.log"
  max_size: 10240  # 10MB
  backup_count: 10

# Frontend settings
app:
  static_folder: "../frontend/dist"
  static_url_path: ""

# API rate limits
rate_limits:
  auth.token: "5 per minute"
  api.transcriptions: "10 per minute"
  api.translations: "20 per minute"
  api.default: "100 per day"

# Swagger documentation
swagger:
  title: "Medical Transcription API"
  version: "1.0.0"
  description: "API for medical audio transcription and translation"
  openapi_version: "3.0.2"
  contact_email: "ebenezerbrant44@gmail.com"

# API settings
api:
  base_url: "/api"